spring:
  application:
    name: meppidoupkteiphhqnda
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      username: ${MONGO_USER}
      password:
      uri: mongodb://${MGHOST}:${MGPORT}/${MONGO_DB}
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT}

