spring:
  application:
    name: meppidoupkteiphhqnda
  datasource:
    password: password
    url: jdbc:h2:mem:my_bpm
    username: h2
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      username: mongo
      password: password
      uri: mongodb://localhost:27017/my_bpm

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081
